"""Add wechat group ID in prod daily view table

Revision ID: 2fb06a9f2264
Revises: 067f3b34e617
Create Date: 2020-11-30 17:49:58.644035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb06a9f2264'
down_revision = '067f3b34e617'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbot_product_daily_view', sa.Column('wechat_group_id', sa.CHAR(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chatbot_product_daily_view', 'wechat_group_id')
    # ### end Alembic commands ###
