"""add dialog tags

Revision ID: 357f7c5a36c1
Revises: f79a6596f361
Create Date: 2020-12-14 19:33:49.235165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '357f7c5a36c1'
down_revision = 'f79a6596f361'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_dialog_tags',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_name', sa.String(length=16), nullable=True),
    sa.Column('dialog_id', sa.Integer(), nullable=True),
    sa.Column('add_user_id', sa.Integer(), nullable=True),
    sa.Column('del_user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_tags',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('tag_name', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('tag_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_tags')
    op.drop_table('chatbot_dialog_tags')
    # ### end Alembic commands ###
