"""Add Wechat group be_at flag

Revision ID: 3812ec1be6c0
Revises: c82124199aed
Create Date: 2021-01-08 12:53:52.905901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3812ec1be6c0'
down_revision = 'c82124199aed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('CreateTime', table_name='wechat_article')
    op.drop_index('WechatID', table_name='wechat_article')
    op.drop_index('WechatIDxCreateTime', table_name='wechat_article')
    op.add_column('wechat_group_bot_config', sa.Column('be_at', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wechat_group_bot_config', 'be_at')
    op.create_index('WechatIDxCreateTime', 'wechat_article', ['id', 'doc_ct'], unique=False)
    op.create_index('WechatID', 'wechat_article', ['wxid'], unique=False)
    op.create_index('CreateTime', 'wechat_article', ['doc_ct'], unique=False)
    # ### end Alembic commands ###
