"""permission is super admin

Revision ID: 84999e28a750
Revises: 13fd32b3e3eb
Create Date: 2020-11-25 10:35:09.316750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84999e28a750'
down_revision = '13fd32b3e3eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('is_super_admin', sa.BOOLEAN(), nullable=True, comment='超级管理员独有'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'is_super_admin')
    # ### end Alembic commands ###
