"""permission

Revision ID: 87edb138887c
Revises: 7c41f648eb71
Create Date: 2020-11-20 12:02:33.084716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87edb138887c'
down_revision = '7c41f648eb71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False, comment='主键ID'),
    sa.Column('name', sa.String(length=127), nullable=True, comment='名称'),
    sa.Column('url', sa.String(length=127), nullable=False, comment='路由'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=50), nullable=False, comment='角色名'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('map_role_permission',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.Column('permission_id', sa.Integer(), nullable=False, comment='权限ID'),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('map_user_role',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.Integer(), nullable=False, comment='角色ID'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('map_user_role')
    op.drop_table('map_role_permission')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
