"""set user_stat ts unique

Revision ID: 8f918e2ae383
Revises: dc134186812c
Create Date: 2021-02-22 10:15:10.336789

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f918e2ae383'
down_revision = 'dc134186812c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'chatbot_user_stat', ['ts'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chatbot_user_stat', type_='unique')
    # ### end Alembic commands ###
