"""Add Wechat group bot config

Revision ID: 9284ad872a1e
Revises: 357f7c5a36c1
Create Date: 2020-12-24 17:31:03.219593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9284ad872a1e'
down_revision = '357f7c5a36c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_group_bot_config',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_group_id', sa.CHAR(length=32), nullable=True),
    sa.Column('bot_id', sa.Integer(), nullable=True),
    sa.Column('share_token', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wechat_group_bot_config')
    # ### end Alembic commands ###
