"""users

Revision ID: a64ce51f375e
Revises: 87edb138887c
Create Date: 2020-11-23 13:17:16.929638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64ce51f375e'
down_revision = '87edb138887c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('menu', sa.String(length=63), nullable=False, comment='菜单'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('permissions', 'menu')
    # ### end Alembic commands ###
