"""chatbot

Revision ID: b5dbe1db312c
Revises: 84999e28a750
Create Date: 2020-11-26 11:36:35.013130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5dbe1db312c'
down_revision = '84999e28a750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chatbot_dialog',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('user_input', sa.Text(), nullable=True),
    sa.Column('bot_reply', sa.Text(), nullable=True),
    sa.Column('bot_raw_reply', sa.Text(), nullable=True),
    sa.Column('similarity', sa.FLOAT(), nullable=True),
    sa.Column('session_id', sa.CHAR(length=32), nullable=True),
    sa.Column('ts', sa.DATETIME(), nullable=True),
    sa.Column('wechat_group_id', sa.CHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_dialog_stat',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dialog_count', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DATETIME(), nullable=True),
    sa.Column('wechat_group_id', sa.CHAR(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_product_daily_view',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_view_count', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_product_view',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.CHAR(length=32), nullable=True),
    sa.Column('product_type', sa.CHAR(length=32), nullable=True),
    sa.Column('product_name', sa.CHAR(length=64), nullable=True),
    sa.Column('ts', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_user_info',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_user_name', sa.CHAR(length=32), nullable=True),
    sa.Column('nick_name', sa.CHAR(length=32), nullable=True),
    sa.Column('head_img', sa.Text(), nullable=True),
    sa.Column('expertise', sa.FLOAT(), nullable=True),
    sa.Column('risk_tolerance', sa.FLOAT(), nullable=True),
    sa.Column('last_action_ts', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_user_stat',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_count', sa.Integer(), nullable=True),
    sa.Column('active_user_count', sa.Integer(), nullable=True),
    sa.Column('ts', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chatbot_tokens',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=32), nullable=True),
    sa.Column('refresh_key', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['chatbot_user_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chatbot_tokens')
    op.drop_table('chatbot_user_stat')
    op.drop_table('chatbot_user_info')
    op.drop_table('chatbot_product_view')
    op.drop_table('chatbot_product_daily_view')
    op.drop_table('chatbot_dialog_stat')
    op.drop_table('chatbot_dialog')
    # ### end Alembic commands ###
