"""Add stage Wechat group bot config

Revision ID: c7d134d215ff
Revises: 9284ad872a1e
Create Date: 2020-12-24 18:40:31.820977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d134d215ff'
down_revision = '9284ad872a1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wechat_group_bot_config', sa.Column('stage', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wechat_group_bot_config', 'stage')
    # ### end Alembic commands ###
