"""Add wechat group message

Revision ID: dc134186812c
Revises: 3812ec1be6c0
Create Date: 2021-02-07 16:08:22.956006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc134186812c'
down_revision = '3812ec1be6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wechat_group_message',
    sa.Column('create_time', sa.DATETIME(), nullable=True),
    sa.Column('update_time', sa.DATETIME(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('chatroomname', sa.Text(), nullable=True),
    sa.Column('message_type', sa.Text(), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('link_source_url', sa.Text(), nullable=True),
    sa.Column('link_title', sa.Text(), nullable=True),
    sa.Column('link_description', sa.Text(), nullable=True),
    sa.Column('link_image_url', sa.Text(), nullable=True),
    sa.Column('pic_url', sa.Text(), nullable=True),
    sa.Column('ts', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wechat_group_message')
    # ### end Alembic commands ###
